# Configuration Gandi Simple Hosting
build:
  # Installation des dépendances
  - npm ci --production=false
  # Build du projet Vite
  - npm run build

# Déploiement
deploy:
  # Le dossier dist contient les fichiers buildés
  source: dist/
  # Destination sur le serveur Gandi
  destination: /
